# Generated by Django 4.2.6 on 2023-11-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chef",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True, verbose_name="Status")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "modified_at",
                    models.DateField(auto_now=True, verbose_name="Modification date"),
                ),
                (
                    "deleted_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Deletion date"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last name"),
                ),
            ],
            options={
                "verbose_name": "Chef",
                "verbose_name_plural": "Chefs",
            },
        ),
    ]
