# Generated by Django 4.2.6 on 2023-10-27 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.TextField(max_length=30, verbose_name='Description')),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chefs.chef')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
