# Generated by Django 4.2.6 on 2023-11-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_recipe_chef"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(default="", verbose_name="Instructions"),
            preserve_default=False,
        ),
    ]
